if(TARGET ${PROJECT_NAME})
    install(DIRECTORY include/ DESTINATION include)

    install(
        EXPORT ${PROJECT_NAME}Targets
        FILE ${PROJECT_NAME}Targets.cmake
        # NAMESPACE ${PROJECT_NAME}Targets::
        NAMESPACE Ahri::
        DESTINATION ${CMAKE_INSTALL_LIB_DIR}/cmake/${PROJECT_NAME}
    )
endif()

if(WIN32)
    set(CPACK_GENERATOR "ZIP")
else()
    set(CPACK_GENERATOR "TGZ")
endif()

include(CPack)
set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${CMAKE_PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT "Sokyoei@Ahri.com")
set(CPACK_PACKAGE_VENDOR "Ahri&Sokyoei&Nono")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Sokyoei's Vision Project")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
